### ISSUE TITLE
接口访问不了呢

### ISSUE THREAD

**Issue by mvpdream** [linzowo/uniapp-elm#3]
![image](https://user-images.githubusercontent.com/16203724/90379436-53e98b80-e0ad-11ea-93c6-c09259eaa26e.png)
![image](https://user-images.githubusercontent.com/16203724/90379487-619f1100-e0ad-11ea-8e55-205cf5636664.png)

**Comment by mvpdream** [comment]
@linzowo

**Comment by linzowo** [comment]
域名到期了，地址变更为 
https://linzowo.github.io/

**Comment by mvpdream** [comment]
> 域名到期了，地址变更为
> https://linzowo.github.io/

按照你的步骤,用hbuilderX运行不起来呢
